# Generated by Django 2.0 on 2019-07-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='polygon',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='polygon',
            name='price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
